//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceManager.UnitTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=dbserver;Initial Catalog=GrundFos_PriceManagerAdv;Integrated Security" +
            "=True")]
        public string GrundFos_PriceManagerAdvConnectionString {
            get {
                return ((string)(this["GrundFos_PriceManagerAdvConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=dbserver;Initial Catalog=GrundFos_PriceManagerAdv_UT;Integrated Secur" +
            "ity=True")]
        public string GrundFos_PriceManagerAdv_UTConnectionString {
            get {
                return ((string)(this["GrundFos_PriceManagerAdv_UTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=dbserver;Initial Catalog=GrundFos_PriceManagerAdv_UT;Persist Security" +
            " Info=True;User ID=grundfos;Password=grundfos")]
        public string GrundFos_PriceManagerAdv_UTConnectionString1 {
            get {
                return ((string)(this["GrundFos_PriceManagerAdv_UTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql.nybblenetwork.com;Initial Catalog=GrundFos_PriceManagerAdv_UT;Per" +
            "sist Security Info=True;User ID=grundfos;Password=grundfos")]
        public string GrundFos_PriceManagerAdv_UTConnectionString2 {
            get {
                return ((string)(this["GrundFos_PriceManagerAdv_UTConnectionString2"]));
            }
        }
    }
}
