//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceManager.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Business {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Business() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriceManager.Common.Resources.Business", typeof(Business).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Está seguro que desea {0} realizados en estos Productos ?.
        /// </summary>
        internal static string ActionConfirmText {
            get {
                return ResourceManager.GetString("ActionConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Productos.
        /// </summary>
        internal static string ActivateProductsAction {
            get {
                return ResourceManager.GetString("ActivateProductsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar a Grupo de Precios.
        /// </summary>
        internal static string AddDistributorsToPriceListAction {
            get {
                return ResourceManager.GetString("AddDistributorsToPriceListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Grupo de Precios.
        /// </summary>
        internal static string AddPagesToPriceListAction {
            get {
                return ResourceManager.GetString("AddPagesToPriceListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover a Maestro Base.
        /// </summary>
        internal static string AddProductsToMasterListAction {
            get {
                return ResourceManager.GetString("AddProductsToMasterListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a categoría.
        /// </summary>
        internal static string AddToCategoryAction {
            get {
                return ResourceManager.GetString("AddToCategoryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Lista de Precios.
        /// </summary>
        internal static string AddToPagelistAction {
            get {
                return ResourceManager.GetString("AddToPagelistAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar al país.
        /// </summary>
        internal static string AddToPricegroupAction {
            get {
                return ResourceManager.GetString("AddToPricegroupAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a selección.
        /// </summary>
        internal static string AddToSelectionAction {
            get {
                return ResourceManager.GetString("AddToSelectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail a Administrador.
        /// </summary>
        internal static string AdministratorReceiveMail {
            get {
                return ResourceManager.GetString("AdministratorReceiveMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        internal static string AdminTooltip {
            get {
                return ResourceManager.GetString("AdminTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50Hz/60Hz.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amarillo.
        /// </summary>
        internal static string Amarillo {
            get {
                return ResourceManager.GetString("Amarillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobada.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar Cambios.
        /// </summary>
        internal static string ApprovePriceListItemsAction {
            get {
                return ResourceManager.GetString("ApprovePriceListItemsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azul.
        /// </summary>
        internal static string Azul {
            get {
                return ResourceManager.GetString("Azul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50/60 Hz.
        /// </summary>
        internal static string BothFrecuency {
            get {
                return ResourceManager.GetString("BothFrecuency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria 1.
        /// </summary>
        internal static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria 2.
        /// </summary>
        internal static string Category2 {
            get {
                return ResourceManager.GetString("Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria 3.
        /// </summary>
        internal static string Category3 {
            get {
                return ResourceManager.GetString("Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        internal static string CategoryType1 {
            get {
                return ResourceManager.GetString("CategoryType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        internal static string CategoryType2 {
            get {
                return ResourceManager.GetString("CategoryType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string CategoryType3 {
            get {
                return ResourceManager.GetString("CategoryType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string CategoryType4 {
            get {
                return ResourceManager.GetString("CategoryType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea.
        /// </summary>
        internal static string CategoryType5 {
            get {
                return ResourceManager.GetString("CategoryType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string CategoryType6 {
            get {
                return ResourceManager.GetString("CategoryType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string CodeError {
            get {
                return ResourceManager.GetString("CodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones Comerciales.
        /// </summary>
        internal static string ComercialCondition {
            get {
                return ResourceManager.GetString("ComercialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string creationBtn {
            get {
                return ResourceManager.GetString("creationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monedas.
        /// </summary>
        internal static string CurrencyTitle {
            get {
                return ResourceManager.GetString("CurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar productos.
        /// </summary>
        internal static string DeactivateProductsAction {
            get {
                return ResourceManager.GetString("DeactivateProductsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        internal static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea cambiar el estado el distribuidor {0} ?.
        /// </summary>
        internal static string DistributorActivity {
            get {
                return ResourceManager.GetString("DistributorActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Canal de Ventas.
        /// </summary>
        internal static string DistributorType {
            get {
                return ResourceManager.GetString("DistributorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrador.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto Duplicado.
        /// </summary>
        internal static string DuplicatedProduct {
            get {
                return ResourceManager.GetString("DuplicatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea eliminar la Categoría {0} del sistema ?.
        /// </summary>
        internal static string EraseCategory {
            get {
                return ResourceManager.GetString("EraseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar de Lista de Precios.
        /// </summary>
        internal static string EraseFromCatalogPageAction {
            get {
                return ResourceManager.GetString("EraseFromCatalogPageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar de Grupo de Precio Actual.
        /// </summary>
        internal static string EraseFromPriceListAction {
            get {
                return ResourceManager.GetString("EraseFromPriceListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar de la selección actual.
        /// </summary>
        internal static string EraseFromSelectionAction {
            get {
                return ResourceManager.GetString("EraseFromSelectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea cambiar el estado del Grupo de Precios {0} ?.
        /// </summary>
        internal static string EraseList {
            get {
                return ResourceManager.GetString("EraseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea eliminar {0} del sistema ?.
        /// </summary>
        internal static string EraseLookup {
            get {
                return ResourceManager.GetString("EraseLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea eliminar la Política de Precios {0} del sistema ?.
        /// </summary>
        internal static string ErasePriceCalculation {
            get {
                return ResourceManager.GetString("ErasePriceCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Value.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Translation Value.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en: .
        /// </summary>
        internal static string ErrorIn {
            get {
                return ResourceManager.GetString("ErrorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.csv.
        /// </summary>
        internal static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Excel.
        /// </summary>
        internal static string ExportToExcelAction {
            get {
                return ResourceManager.GetString("ExportToExcelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a PDF.
        /// </summary>
        internal static string ExportToPdfAction {
            get {
                return ResourceManager.GetString("ExportToPdfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        internal static string Frecuency {
            get {
                return ResourceManager.GetString("Frecuency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string GridViewColumnAddress {
            get {
                return ResourceManager.GetString("GridViewColumnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuste.
        /// </summary>
        internal static string GridViewColumnAdjust {
            get {
                return ResourceManager.GetString("GridViewColumnAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string GridViewColumnCategory {
            get {
                return ResourceManager.GetString("GridViewColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paginas Asignadas.
        /// </summary>
        internal static string GridViewColumnChildTotal {
            get {
                return ResourceManager.GetString("GridViewColumnChildTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string GridViewColumnCity {
            get {
                return ResourceManager.GetString("GridViewColumnCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string GridViewColumnCode {
            get {
                return ResourceManager.GetString("GridViewColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string GridViewColumnContact {
            get {
                return ResourceManager.GetString("GridViewColumnContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor de Conversión.
        /// </summary>
        internal static string GridViewColumnConvertionFactor {
            get {
                return ResourceManager.GetString("GridViewColumnConvertionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string GridViewColumnCountry {
            get {
                return ResourceManager.GetString("GridViewColumnCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTM.
        /// </summary>
        internal static string GridViewColumnCTM {
            get {
                return ResourceManager.GetString("GridViewColumnCTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTR.
        /// </summary>
        internal static string GridViewColumnCTR {
            get {
                return ResourceManager.GetString("GridViewColumnCTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string GridViewColumnCurrency {
            get {
                return ResourceManager.GetString("GridViewColumnCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string GridViewColumnDate {
            get {
                return ResourceManager.GetString("GridViewColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string GridViewColumnDescription {
            get {
                return ResourceManager.GetString("GridViewColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        internal static string GridViewColumnDiscount {
            get {
                return ResourceManager.GetString("GridViewColumnDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal de Ventas.
        /// </summary>
        internal static string GridViewColumnDistributor {
            get {
                return ResourceManager.GetString("GridViewColumnDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string GridViewColumnDistributorName {
            get {
                return ResourceManager.GetString("GridViewColumnDistributorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obs. del Canal de Ventas.
        /// </summary>
        internal static string GridViewColumnDistributorObservation {
            get {
                return ResourceManager.GetString("GridViewColumnDistributorObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string GridViewColumnFax {
            get {
                return ResourceManager.GetString("GridViewColumnFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string GridViewColumnFile {
            get {
                return ResourceManager.GetString("GridViewColumnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula.
        /// </summary>
        internal static string GridViewColumnFormula {
            get {
                return ResourceManager.GetString("GridViewColumnFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula Secundaria.
        /// </summary>
        internal static string GridViewColumnFormulaSec {
            get {
                return ResourceManager.GetString("GridViewColumnFormulaSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        internal static string GridViewColumnFrequency {
            get {
                return ResourceManager.GetString("GridViewColumnFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP.
        /// </summary>
        internal static string GridViewColumnGRP {
            get {
                return ResourceManager.GetString("GridViewColumnGRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores.
        /// </summary>
        internal static string GridViewColumnImportError {
            get {
                return ResourceManager.GetString("GridViewColumnImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificados.
        /// </summary>
        internal static string GridViewColumnImportMod {
            get {
                return ResourceManager.GetString("GridViewColumnImportMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevos.
        /// </summary>
        internal static string GridViewColumnImportNew {
            get {
                return ResourceManager.GetString("GridViewColumnImportNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Venta.
        /// </summary>
        internal static string GridViewColumnIncoterm {
            get {
                return ResourceManager.GetString("GridViewColumnIncoterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string GridViewColumnIndex {
            get {
                return ResourceManager.GetString("GridViewColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días de Demora.
        /// </summary>
        internal static string GridViewColumnLeadTime {
            get {
                return ResourceManager.GetString("GridViewColumnLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        internal static string GridViewColumnLevel {
            get {
                return ResourceManager.GetString("GridViewColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string GridViewColumnListCountry {
            get {
                return ResourceManager.GetString("GridViewColumnListCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string GridViewColumnListCurrency {
            get {
                return ResourceManager.GetString("GridViewColumnListCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string GridViewColumnListID {
            get {
                return ResourceManager.GetString("GridViewColumnListID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Precios.
        /// </summary>
        internal static string GridViewColumnListName {
            get {
                return ResourceManager.GetString("GridViewColumnListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string GridViewColumnLookupType {
            get {
                return ResourceManager.GetString("GridViewColumnLookupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string GridViewColumnModel {
            get {
                return ResourceManager.GetString("GridViewColumnModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string GridViewColumnName {
            get {
                return ResourceManager.GetString("GridViewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        internal static string GridViewColumnNetPrice {
            get {
                return ResourceManager.GetString("GridViewColumnNetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string GridViewColumnNumber {
            get {
                return ResourceManager.GetString("GridViewColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string GridViewColumnObservations {
            get {
                return ResourceManager.GetString("GridViewColumnObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padre.
        /// </summary>
        internal static string GridViewColumnParent {
            get {
                return ResourceManager.GetString("GridViewColumnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Pago.
        /// </summary>
        internal static string GridViewColumnPaymentTerm {
            get {
                return ResourceManager.GetString("GridViewColumnPaymentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCR.
        /// </summary>
        internal static string GridViewColumnPCR {
            get {
                return ResourceManager.GetString("GridViewColumnPCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string GridViewColumnPrice {
            get {
                return ResourceManager.GetString("GridViewColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        internal static string GridViewColumnPriceList {
            get {
                return ResourceManager.GetString("GridViewColumnPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Precios.
        /// </summary>
        internal static string GridViewColumnPriceListName {
            get {
                return ResourceManager.GetString("GridViewColumnPriceListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV.
        /// </summary>
        internal static string GridViewColumnPriceSell {
            get {
                return ResourceManager.GetString("GridViewColumnPriceSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioridad.
        /// </summary>
        internal static string GridViewColumnPriority {
            get {
                return ResourceManager.GetString("GridViewColumnPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Productos.
        /// </summary>
        internal static string GridViewColumnProductsTotal {
            get {
                return ResourceManager.GetString("GridViewColumnProductsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string GridViewColumnProvider {
            get {
                return ResourceManager.GetString("GridViewColumnProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Publicación.
        /// </summary>
        internal static string GridViewColumnPublishDate {
            get {
                return ResourceManager.GetString("GridViewColumnPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras de año actual.
        /// </summary>
        internal static string GridViewColumnPurchaseYTD {
            get {
                return ResourceManager.GetString("GridViewColumnPurchaseYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras de año anterior.
        /// </summary>
        internal static string GridViewColumnPurchPrevYear {
            get {
                return ResourceManager.GetString("GridViewColumnPurchPrevYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedencia.
        /// </summary>
        internal static string GridViewColumnSource {
            get {
                return ResourceManager.GetString("GridViewColumnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string GridViewColumnStatus {
            get {
                return ResourceManager.GetString("GridViewColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Impuesto.
        /// </summary>
        internal static string GridViewColumnTaxCode {
            get {
                return ResourceManager.GetString("GridViewColumnTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        internal static string GridViewColumnTelephone {
            get {
                return ResourceManager.GetString("GridViewColumnTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.
        /// </summary>
        internal static string GridViewColumnTP {
            get {
                return ResourceManager.GetString("GridViewColumnTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string GridViewColumnType {
            get {
                return ResourceManager.GetString("GridViewColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string GridViewColumnUser {
            get {
                return ResourceManager.GetString("GridViewColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string GridViewColumnValue {
            get {
                return ResourceManager.GetString("GridViewColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Vigencia.
        /// </summary>
        internal static string GridViewColumnVigencyDate {
            get {
                return ResourceManager.GetString("GridViewColumnVigencyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP.
        /// </summary>
        internal static string GRP {
            get {
                return ResourceManager.GetString("GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda GRP.
        /// </summary>
        internal static string GRPCurrency {
            get {
                return ResourceManager.GetString("GRPCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Guid_ {
            get {
                return ResourceManager.GetString("Guid?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50Hz.
        /// </summary>
        internal static string Hz50 {
            get {
                return ResourceManager.GetString("Hz50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60Hz.
        /// </summary>
        internal static string Hz60 {
            get {
                return ResourceManager.GetString("Hz60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inválido.
        /// </summary>
        internal static string ImportStatusInvalid {
            get {
                return ResourceManager.GetString("ImportStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesado.
        /// </summary>
        internal static string ImportStatusProcessed {
            get {
                return ResourceManager.GetString("ImportStatusProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargado.
        /// </summary>
        internal static string ImportStatusUploaded {
            get {
                return ResourceManager.GetString("ImportStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importación.
        /// </summary>
        internal static string ImportTitle {
            get {
                return ResourceManager.GetString("ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompleto.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inválido.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        internal static string LookUpTitle {
            get {
                return ResourceManager.GetString("LookUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificada.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar precio de lista.
        /// </summary>
        internal static string ModifyPricesAction {
            get {
                return ResourceManager.GetString("ModifyPricesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover a Fuera de Lista.
        /// </summary>
        internal static string MoveProductsOutOfListAction {
            get {
                return ResourceManager.GetString("MoveProductsOutOfListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar de este País.
        /// </summary>
        internal static string MoveProductsToBaseListAction {
            get {
                return ResourceManager.GetString("MoveProductsToBaseListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover a Fuera de Lista.
        /// </summary>
        internal static string MoveProductsToOutOfListAction {
            get {
                return ResourceManager.GetString("MoveProductsToOutOfListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a categoría.
        /// </summary>
        internal static string MoveToCategoryAction {
            get {
                return ResourceManager.GetString("MoveToCategoryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a País.
        /// </summary>
        internal static string MoveToPricegroupAction {
            get {
                return ResourceManager.GetString("MoveToPricegroupAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Grupo de Precios.
        /// </summary>
        internal static string MoveToPriceListAction {
            get {
                return ResourceManager.GetString("MoveToPriceListAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a selección.
        /// </summary>
        internal static string MoveToSelectionAction {
            get {
                return ResourceManager.GetString("MoveToSelectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan datos obligatorios (Cod Grunfos o Cod Proveedor y Proveedor).
        /// </summary>
        internal static string ObligatoryData {
            get {
                return ResourceManager.GetString("ObligatoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuera de Lista.
        /// </summary>
        internal static string OutOfList {
            get {
                return ResourceManager.GetString("OutOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea cambiar el estado de la lista de precios {0} ?.
        /// </summary>
        internal static string PageListActivity {
            get {
                return ResourceManager.GetString("PageListActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Precios.
        /// </summary>
        internal static string PageListTitle {
            get {
                return ResourceManager.GetString("PageListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Pago.
        /// </summary>
        internal static string PaymentTerm {
            get {
                return ResourceManager.GetString("PaymentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pend. Aprobar.
        /// </summary>
        internal static string PendingToApprovecount {
            get {
                return ResourceManager.GetString("PendingToApprovecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda PL.
        /// </summary>
        internal static string PLCurrency {
            get {
                return ResourceManager.GetString("PLCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string PriceBaseDisable {
            get {
                return ResourceManager.GetString("PriceBaseDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuera de Lista.
        /// </summary>
        internal static string PriceBaseNotVerified {
            get {
                return ResourceManager.GetString("PriceBaseNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string PriceBaseVerified {
            get {
                return ResourceManager.GetString("PriceBaseVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestros de Precios.
        /// </summary>
        internal static string PriceGroupTitle {
            get {
                return ResourceManager.GetString("PriceGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo se encuentra vacio o en uso. Cierrelo antes de continuar..
        /// </summary>
        internal static string PriceImportationEmptyFileError {
            get {
                return ResourceManager.GetString("PriceImportationEmptyFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error en la carga del archivo. Por favor, revíselo y vuelva a intentarlo..
        /// </summary>
        internal static string PriceImportationError {
            get {
                return ResourceManager.GetString("PriceImportationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique que el archivo sea de extension CSV..
        /// </summary>
        internal static string PriceImportationExtensionError {
            get {
                return ResourceManager.GetString("PriceImportationExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inválido.
        /// </summary>
        internal static string PriceImportInvalid {
            get {
                return ResourceManager.GetString("PriceImportInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesado.
        /// </summary>
        internal static string PriceImportProcessed {
            get {
                return ResourceManager.GetString("PriceImportProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subido.
        /// </summary>
        internal static string PriceImportUploaded {
            get {
                return ResourceManager.GetString("PriceImportUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificado.
        /// </summary>
        internal static string PriceImportVerified {
            get {
                return ResourceManager.GetString("PriceImportVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificado/Errores.
        /// </summary>
        internal static string PriceImportVerifiedSomeValid {
            get {
                return ResourceManager.GetString("PriceImportVerifiedSomeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Lista de Precio.
        /// </summary>
        internal static string PriceListType {
            get {
                return ResourceManager.GetString("PriceListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string PriceManager_Business_Filters_CurrencyFilter_ID {
            get {
                return ResourceManager.GetString("PriceManager.Business.Filters.CurrencyFilter.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string PriceManager_Business_Filters_LinkedDropDownFilters {
            get {
                return ResourceManager.GetString("PriceManager.Business.Filters.LinkedDropDownFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string PriceManager_Business_Filters_LinkedDropDownFilters_ID {
            get {
                return ResourceManager.GetString("PriceManager.Business.Filters.LinkedDropDownFilters.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación.
        /// </summary>
        internal static string PriceManager_Core_Application {
            get {
                return ResourceManager.GetString("PriceManager.Core.Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación.
        /// </summary>
        internal static string PriceManager_Core_Application_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Application.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        internal static string PriceManager_Core_Area {
            get {
                return ResourceManager.GetString("PriceManager.Core.Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        internal static string PriceManager_Core_Area_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Area.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        internal static string PriceManager_Core_CatalogPage {
            get {
                return ResourceManager.GetString("PriceManager.Core.CatalogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        internal static string PriceManager_Core_CatalogPage_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.CatalogPage.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padre.
        /// </summary>
        internal static string PriceManager_Core_CatalogPage_Parent {
            get {
                return ResourceManager.GetString("PriceManager.Core.CatalogPage.Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string PriceManager_Core_CategoryBase {
            get {
                return ResourceManager.GetString("PriceManager.Core.CategoryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_CategoryPageStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.CategoryPageStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string PriceManager_Core_Country_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Country.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTR.
        /// </summary>
        internal static string PriceManager_Core_CtrRange_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.CtrRange.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string PriceManager_Core_Currency_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Currency.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal de Ventas.
        /// </summary>
        internal static string PriceManager_Core_Distributor_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Distributor.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_DistributorStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.DistributorStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        internal static string PriceManager_Core_Family {
            get {
                return ResourceManager.GetString("PriceManager.Core.Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        internal static string PriceManager_Core_Family_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Family.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        internal static string PriceManager_Core_Frequency {
            get {
                return ResourceManager.GetString("PriceManager.Core.Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        internal static string PriceManager_Core_Frequency_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Frequency.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_ImportStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.ImportStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Venta.
        /// </summary>
        internal static string PriceManager_Core_Incoterm_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Incoterm.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string PriceManager_Core_IndexPrice_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.IndexPrice.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea.
        /// </summary>
        internal static string PriceManager_Core_Line {
            get {
                return ResourceManager.GetString("PriceManager.Core.Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea.
        /// </summary>
        internal static string PriceManager_Core_Line_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Line.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string PriceManager_Core_Lookup_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Lookup.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Pago.
        /// </summary>
        internal static string PriceManager_Core_Lookup_Payment {
            get {
                return ResourceManager.GetString("PriceManager.Core.Lookup.Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string PriceManager_Core_LookupType_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.LookupType.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Pago.
        /// </summary>
        internal static string PriceManager_Core_PaymentTerm_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PaymentTerm.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificado desde .
        /// </summary>
        internal static string PriceManager_Core_PriceBase_TimeStamp_ModifiedOn {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceBase.TimeStamp.ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_PriceBaseStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceBaseStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioridad.
        /// </summary>
        internal static string PriceManager_Core_PriceCalculationPriority_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceCalculationPriority.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string PriceManager_Core_PriceGroup_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceGroup.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Importado.
        /// </summary>
        internal static string PriceManager_Core_PriceImport_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceImport.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Precios.
        /// </summary>
        internal static string PriceManager_Core_PriceList_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceList.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_PriceListStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PriceListStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        internal static string PriceManager_Core_Product_Description {
            get {
                return ResourceManager.GetString("PriceManager_Core_Product_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad del producto.
        /// </summary>
        internal static string PriceManager_Core_ProductStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.ProductStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string PriceManager_Core_ProductType {
            get {
                return ResourceManager.GetString("PriceManager.Core.ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string PriceManager_Core_ProductType_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.ProductType.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string PriceManager_Core_Provider_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Provider.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_ProviderStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.ProviderStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_PublishListStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.PublishListStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_QuoteStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.QuoteStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección.
        /// </summary>
        internal static string PriceManager_Core_Selection_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.Selection.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string PriceManager_Core_WorkListItemStatus_ID {
            get {
                return ResourceManager.GetString("PriceManager.Core.WorkListItemStatus.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de Precios.
        /// </summary>
        internal static string PricePoliticTitle {
            get {
                return ResourceManager.GetString("PricePoliticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesado.
        /// </summary>
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea cambiar el estado del proveedor {0} ?.
        /// </summary>
        internal static string ProviderActivity {
            get {
                return ResourceManager.GetString("ProviderActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string ProviderTitle {
            get {
                return ResourceManager.GetString("ProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar Cambios.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicada.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Condición de Compra.
        /// </summary>
        internal static string PurchaseType {
            get {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío adjunto con cotización solicitada..
        /// </summary>
        internal static string QuoteBody {
            get {
                return ResourceManager.GetString("QuoteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Cotización.
        /// </summary>
        internal static string QuoteCondition {
            get {
                return ResourceManager.GetString("QuoteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Introducción de Cotización.
        /// </summary>
        internal static string QuoteIntroText {
            get {
                return ResourceManager.GetString("QuoteIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cotización # {0}, {1} ha sido rechazada..
        /// </summary>
        internal static string QuoteReject {
            get {
                return ResourceManager.GetString("QuoteReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizaciones.
        /// </summary>
        internal static string QuoteTitle {
            get {
                return ResourceManager.GetString("QuoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia de Cotización.
        /// </summary>
        internal static string QuoteVigency {
            get {
                return ResourceManager.GetString("QuoteVigency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazada.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar Cambios.
        /// </summary>
        internal static string RejectPriceListItemsAction {
            get {
                return ResourceManager.GetString("RejectPriceListItemsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea rechazar la cotización {0} del sistema ?.
        /// </summary>
        internal static string RejectQuote {
            get {
                return ResourceManager.GetString("RejectQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar de categoría.
        /// </summary>
        internal static string RemoveFromCategoryAction {
            get {
                return ResourceManager.GetString("RemoveFromCategoryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rojo.
        /// </summary>
        internal static string Rojo {
            get {
                return ResourceManager.GetString("Rojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro ?.
        /// </summary>
        internal static string RollbackAttributeHistory {
            get {
                return ResourceManager.GetString("RollbackAttributeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro ?.
        /// </summary>
        internal static string RollbackBaseHistory {
            get {
                return ResourceManager.GetString("RollbackBaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro ?.
        /// </summary>
        internal static string RollbackPriceListHistory {
            get {
                return ResourceManager.GetString("RollbackPriceListHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabar precios.
        /// </summary>
        internal static string SavePricesAction {
            get {
                return ResourceManager.GetString("SavePricesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviada.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string System_Guid_UserId {
            get {
                return ResourceManager.GetString("System.Guid.UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Categoría.
        /// </summary>
        internal static string System_Type_FullName {
            get {
                return ResourceManager.GetString("System.Type.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string System_Web_UI_Pair_TimeStampCheck {
            get {
                return ResourceManager.GetString("System_Web_UI_Pair_TimeStampCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar de categoría.
        /// </summary>
        internal static string TakeOutFromCategoryAction {
            get {
                return ResourceManager.GetString("TakeOutFromCategoryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción supera los 512 caracteres.
        /// </summary>
        internal static string Text512Charactes {
            get {
                return ResourceManager.GetString("Text512Charactes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo supera los 64 caracteres.
        /// </summary>
        internal static string Text64Characters {
            get {
                return ResourceManager.GetString("Text64Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string ToCurrencyOriginal {
            get {
                return ResourceManager.GetString("ToCurrencyOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string tooltipC__243_digo {
            get {
                return ResourceManager.GetString("tooltipC&#243;digo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribución Nominal.
        /// </summary>
        internal static string tooltipCTM {
            get {
                return ResourceManager.GetString("tooltipCTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribución Porcentual.
        /// </summary>
        internal static string tooltipCTR {
            get {
                return ResourceManager.GetString("tooltipCTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        internal static string tooltipFrecuencia {
            get {
                return ResourceManager.GetString("tooltipFrecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Sugerido.
        /// </summary>
        internal static string tooltipGRP {
            get {
                return ResourceManager.GetString("tooltipGRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string tooltipIndex {
            get {
                return ResourceManager.GetString("tooltipIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string tooltipModelo {
            get {
                return ResourceManager.GetString("tooltipModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Lista.
        /// </summary>
        internal static string tooltipP_Neto {
            get {
                return ResourceManager.GetString("tooltipP.Neto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Lista.
        /// </summary>
        internal static string tooltipPL {
            get {
                return ResourceManager.GetString("tooltipPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string tooltipProveedor {
            get {
                return ResourceManager.GetString("tooltipProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Venta.
        /// </summary>
        internal static string tooltipPV {
            get {
                return ResourceManager.GetString("tooltipPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Compra.
        /// </summary>
        internal static string tooltipTP {
            get {
                return ResourceManager.GetString("tooltipTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.
        /// </summary>
        internal static string TP {
            get {
                return ResourceManager.GetString("TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda TP.
        /// </summary>
        internal static string TPCurrency {
            get {
                return ResourceManager.GetString("TPCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar todo.
        /// </summary>
        internal static string UpdateAllCurrencyRate {
            get {
                return ResourceManager.GetString("UpdateAllCurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Esta seguro que desea actualizar la Moneda {0} del sistema ?.
        /// </summary>
        internal static string UpdateCurrency {
            get {
                return ResourceManager.GetString("UpdateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subido.
        /// </summary>
        internal static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inválida..
        /// </summary>
        internal static string Validator_Invalid_Date {
            get {
                return ResourceManager.GetString("Validator_Invalid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango inválido..
        /// </summary>
        internal static string Validator_Invalid_Range {
            get {
                return ResourceManager.GetString("Validator_Invalid_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificado.
        /// </summary>
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificado/Errores.
        /// </summary>
        internal static string VerifiedSomeInvalid {
            get {
                return ResourceManager.GetString("VerifiedSomeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Página Definida.
        /// </summary>
        internal static string WithOutCatalogPage {
            get {
                return ResourceManager.GetString("WithOutCatalogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado.
        /// </summary>
        internal static string WorkListItemAdded {
            get {
                return ResourceManager.GetString("WorkListItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado/Modificado.
        /// </summary>
        internal static string WorkListItemAddedMod {
            get {
                return ResourceManager.GetString("WorkListItemAddedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobado.
        /// </summary>
        internal static string WorkListItemApproved {
            get {
                return ResourceManager.GetString("WorkListItemApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificado.
        /// </summary>
        internal static string WorkListItemModified {
            get {
                return ResourceManager.GetString("WorkListItemModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicado.
        /// </summary>
        internal static string WorkListItemPublished {
            get {
                return ResourceManager.GetString("WorkListItemPublished", resourceCulture);
            }
        }
    }
}
